version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            UNIQUE_TAG=$(date +%Y%m%d%H%M%S)
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
            echo "export UNIQUE_TAG='$UNIQUE_TAG'" >> $BASH_ENV

  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install and Update Trivy DB
          command: |
            sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install -y trivy
            trivy image --download-db-only
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            trivy image --severity HIGH,CRITICAL $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG

  sign:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Sign the Docker image with Cosign
          command: |
            echo $COSIGN_PRIVATE_KEY | base64 --decode > cosign.key
            export COSIGN_PASSWORD=$COSIGN_PASSWORD
            COSIGN_VERSION="v2.2.3"
            if [ ! -f /usr/local/bin/cosign ]; then
              wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
              sudo chmod +x cosign
              sudo mv cosign /usr/local/bin/cosign
            fi
            cosign sign --key cosign.key $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG

workflows:
  version: 2
  full_workflow:
    jobs:
      - build
      - scan:
          requires:
            - build
      - sign:
          requires:
            - scan
