version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login ${REGISTRY} --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo ${IMAGE_NAME} | tr '[:upper:]' '[:lower:]')
            docker build -t ${REGISTRY}/${LOWERCASE_IMAGE_NAME}:latest .
            docker push ${REGISTRY}/${LOWERCASE_IMAGE_NAME}:latest

  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Trivy
          command: |
            sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) stable | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            LOWERCASE_IMAGE_NAME=$(echo ${IMAGE_NAME} | tr '[:upper:]' '[:lower:]')
            trivy image --severity HIGH,CRITICAL ${REGISTRY}/${LOWERCASE_IMAGE_NAME}:latest

  sign:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install cosign
          command: |
            COSIGN_VERSION="v2.2.3"
            sudo wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
            sudo chmod +x cosign
            sudo mv cosign /usr/local/bin/cosign
      - run:
          name: Sign the published Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo ${IMAGE_NAME} | tr '[:upper:]' '[:lower:]')
            cosign sign --yes ${REGISTRY}/${LOWERCASE_IMAGE_NAME}:latest

workflows:
  version: 2
  build-scan-sign:
    jobs:
      - build
      - scan:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - dev-2
                - circleci-project-setup
            tags:
              only: /^v.*/
      - sign:
          requires:
            - scan
          filters:
            branches:
              only:
                - main
                - dev-2
                - circleci-project-setup
            tags:
              only: /^v.*/
