version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Generate unique tag and build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            TAG="build-${CIRCLE_BUILD_NUM}" # Or use TAG=$(date +%Y%m%d%H%M%S) for datetime based tagging
            echo "Using TAG: $TAG for $LOWERCASE_IMAGE_NAME"
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:$TAG .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:$TAG
            echo "export TAG='$TAG'" >> $BASH_ENV

  scan_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Trivy and scan
          command: |
            sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy
            trivy image --severity HIGH,CRITICAL $REGISTRY/$LOWERCASE_IMAGE_NAME:$TAG

  sign_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Cosign and sign
          command: |
            COSIGN_VERSION="v2.2.3"
            wget https://github.com/sigstore/cosign/releases/download/$COSIGN_VERSION/cosign-linux-amd64 -O cosign
            sudo chmod +x cosign
            sudo mv cosign /usr/local/bin/cosign
            echo $COSIGN_PRIVATE_KEY | base64 --decode > cosign.key
            cosign sign --key cosign.key $REGISTRY/$LOWERCASE_IMAGE_NAME:$TAG

workflows:
  version: 2
  build_scan_sign_workflow:
    jobs:
      - build_and_push
      - scan_image:
          requires:
            - build_and_push
      - sign_image:
          requires:
            - scan_image

