version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            UNIQUE_TAG=$(date +%Y%m%d%H%M%S)
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
            echo "export UNIQUE_TAG='$UNIQUE_TAG'" >> $BASH_ENV

  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - trivy-db-{{ checksum "trivy-db" }}
      - run:
          name: Install Trivy
          command: |
            if [ ! -f /usr/local/bin/trivy ]; then
              sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
              echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
              sudo apt-get update && sudo apt-get install trivy
            fi
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            trivy image --severity HIGH,CRITICAL $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
      - save_cache:
          key: trivy-db-{{ checksum "trivy-db" }}
          paths:
            - /root/.cache/trivy

  sign:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - cosign-{{ .Environment.COSIGN_VERSION }}
      - run:
          name: Install Cosign
          command: |
            if [ ! -f /usr/local/bin/cosign ]; then
              COSIGN_VERSION="v2.2.3"
              wget https://github.com/sigstore/cosign/releases/download/$COSIGN_VERSION/cosign-linux-amd64 -O cosign
              sudo chmod +x cosign
              sudo mv cosign /usr/local/bin/cosign
              echo $COSIGN_VERSION > /tmp/cosign-version
            fi
      - save_cache:
          key: cosign-{{ .Environment.COSIGN_VERSION }}
          paths:
            - /usr/local/bin/cosign
            - /tmp/cosign-version
      - run:
          name: Sign the published Docker image
          command: |
            echo $COSIGN_PRIVATE_KEY | base64 --decode > cosign.key
            cosign sign --key cosign.key $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG

workflows:
  version: 2
  build_scan_sign:
    jobs:
      - build
      - scan:
          requires:
            - build
      - sign:
          requires:
            - scan
