version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            UNIQUE_TAG=$(date +%Y%m%d%H%M%S)
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
            echo "export UNIQUE_TAG='$UNIQUE_TAG'" >> $BASH_ENV

  scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - trivy-db-{{ epoch }}
      - run:
          name: Update Trivy DB
          command: |
            sudo trivy image --download-db-only
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            trivy image --severity HIGH,CRITICAL $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
      - save_cache:
          key: trivy-db-{{ epoch }}
          paths:
            - /root/.cache/trivy

  sign:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          keys:
          - cosign-{{ .Environment.COSIGN_VERSION }}
      - run:
          name: Install Cosign if not cached
          command: |
            if [ ! -f /usr/local/bin/cosign ]; then
              COSIGN_VERSION="v2.2.3"
              wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O cosign
              sudo chmod +x cosign
              sudo mv cosign /usr/local/bin/cosign
            fi
      - save_cache:
          key: cosign-{{ .Environment.COSIGN_VERSION }}
          paths:
          - /usr/local/bin/cosign
      - run:
          name: Decode Cosign private key and sign the Docker image
          command: |
            echo $COSIGN_PRIVATE_KEY | base64 --decode > cosign.key
            cosign sign --key cosign.key $REGISTRY/$LOWERCASE_IMAGE_NAME:$UNIQUE_TAG
          environment:
            COSIGN_PASSWORD: $COSIGN_PASSWORD

workflows:
  version: 2
  full_workflow:
    jobs:
      - build
      - scan:
          requires:
            - build
      - sign:
          requires:
            - scan
