version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
 
      - run:
          name: Build and push Docker image, capture digest
          command: |
            LOWERCASE_IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
            docker build -t $REGISTRY/$LOWERCASE_IMAGE_NAME:latest .
            docker push $REGISTRY/$LOWERCASE_IMAGE_NAME:latest
            DIGEST=$(docker image inspect $REGISTRY/$LOWERCASE_IMAGE_NAME:latest --format='{{index .RepoDigests 0}}' | cut -d '@' -f 2)
            echo "export DIGEST='$DIGEST'" >> $BASH_ENV


  scan_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Trivy
          command: |
            sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy
      - run:
          name: Scan Docker image for vulnerabilities
          command: |
            trivy image --severity HIGH,CRITICAL "$REGISTRY/$LOWERCASE_IMAGE_NAME@sha256:$DIGEST"

  sign_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Cosign
          command: |
            COSIGN_VERSION="v2.2.3"
            wget https://github.com/sigstore/cosign/releases/download/$COSIGN_VERSION/cosign-linux-amd64 -O cosign
            sudo chmod +x cosign
            sudo mv cosign /usr/local/bin/cosign
      - run:
          name: Sign the Docker image with Cosign
          command: |
            echo $COSIGN_PRIVATE_KEY | base64 --decode > cosign.key
            cosign sign --key cosign.key $DIGEST

workflows:
  version: 2
  build_scan_sign_workflow:
    jobs:
      - build_and_push
      - scan_image:
          requires:
            - build_and_push
      - sign_image:
          requires:
            - scan_image
