version: 2.1

orbs:
  docker: circleci/docker@2.1

workflows:
  version: 2
  build-and-push:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true

      - run:
          name: Install Cosign
          command: |
            COSIGN_VERSION="v2.2.3"
            sudo wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64 -O /usr/local/bin/cosign
            sudo chmod +x /usr/local/bin/cosign

      - run:
          name: Generate Cosign keys
          command: |
            cosign generate-key-pair
            mkdir -p $HOME/.cosign
            mv cosign.key cosign.pub $HOME/.cosign/

      - persist_to_workspace:
          root: $HOME/.cosign
          paths:
            - .cosign/

      - run:
          name: Build Docker image
          command: |
            LOWERCASE_REGISTRY=$(echo ${REGISTRY} | tr '[:upper:]' '[:lower:]')
            LOWERCASE_IMAGE_NAME=$(echo ${IMAGE_NAME} | tr '[:upper:]' '[:lower:]')
            docker build -t ${myrepository}/${LOWERCASE_IMAGE_NAME}:latest .

      - run:
          name: Push Docker image
          command: |
            docker login ${REGISTRY} -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push ${myrepository}/${LOWERCASE_IMAGE_NAME}:latest

      - attach_workspace:
          at: $HOME

      - run:
          name: Sign Docker image
          command: |
            cosign sign --key .cosign/cosign.key --cert .cosign/cosign.pub --context "fulcio" --yes ${myrepository}/${LOWERCASE_IMAGE_NAME}:latest
